name: deploy
needs: build
runs-on: ubuntu-latest
steps:
  - name: Checkout Repo
    uses: actions/checkout@v2.3.2
  - name: Download Artifact
    uses: actions/download-artifact@v2
    with:
      name: build
      path: build
  - name: Deploy to Firebase
    uses: w9jds/firebase-action@master
    with:
      args: depoy --only hosting
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
